name = "cobblemon-modpack"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da297eab34c277ad38ef279d9095eb77c17cb3af1bdae0a73cde198983fb8f02"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
