name = "cobblemon-modpack"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "462381a62288579d0cb88b5046bcd77ba61f7ee7398c6edce1ba2b33d3353f14"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
datapack-folder = "config/paxi/datapacks"
